/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parseMdict(file: string): Array<DictRecord>
export declare class DictRecord {
  word: string
  definition: string
  constructor(word: string, definition: string)
}
